name: real_time
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  web_socket_channel: ^2.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  image: ^4.1.3
  permission_handler: ^11.0.1
  vibration: ^2.0.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/signs/
    - assets/images/